- Services:
  - Proxmox:
      icon: proxmox.png
      href: https://ip:8006 #fill this in
      description: Proxmox VE
      widget:
        type: proxmox
        url: https://ip:8006 #fill this in
        username: apiuser #fill this in
        password: apikey #fill this in
  - NAS:
      icon: https://www.45drives.com/about/fan-red.png
      href: https://ip:9090 #fill this in
      description: NAS file share
  - Portainer:
      icon: portainer.png
      href: https://ip:9443 #fill this in
      description: Portainer
      widget:
        type: portainer
        url: https://ip:9443 #fill this in
        env: number #fill this in
        key: apikey #fill this in
  - Tailscale:
      icon: tailscale.png
      href: https://login.tailscale.com/admin/machines
      description: Tailscale
      widget:
        type: tailscale
        deviceid: devid #fill this in
        key: apikey #fill this in
- Calendar:
  - ‎:
      widget:
        type: calendar
        firstDayInWeek: sunday
        view: monthly
        maxEvents: 10
        showTime: true
        integrations:
          - type: ical
            defaults: false
            url: myics #fill this in
            name: My Events
            color: violet
            params: null
          - type: ical
            defaults: false
            url: holidayics #fill this in
            name: Holidays
            color: yellow
            params: null
